# Generated by Django 5.0.1 on 2024-02-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentik_core", "0033_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="enabled",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
